administrator/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path("dashboard", views.admin_dashboard,
         name="admin_dashboard"),
    
    path("admin_management", views.admin_management,
         name="admin_management"),
    path("add_admin", views.add_admin,
        name="add_admin"),
    path("update_admin/<int:pk>/", views.update_admin, 
        name="update_admin"),
    path("delete_admin/<int:pk>/", views.delete_admin, 
        name="delete_admin"),

    path("donor_management", views.donor_management,
         name="donor_management"),
    path("add_donor", views.add_donor,
         name="add_donor"),
    path("update_donor/<int:pk>/", views.update_donor, 
        name="update_donor"),
    path("delete_donor/<int:pk>/", views.delete_donor, 
        name="delete_donor"),
    
    path("orphan_management", views.orphan_management,
         name="orphan_management"),
    path("add_orphan", views.add_orphan,
         name="add_orphan"),
    path("update_orphan/<int:pk>/", views.update_orphan,
         name="update_orphan"),
         path("delete_orphan/<int:pk>/", views.delete_orphan,
         name="delete_orphan"),
     path("update_orphan2/<int:pk>/", views.update_orphan2,
         name="update_orphan2"),
    
    path("outing_management", views.outing_management,
         name="outing_management"),
     path("add_outing", views.add_outing,
         name="add_outing"),
    path("update_outing/<int:pk>/", views.update_outing,
         name="update_outing"),
         path("delete_outing/<int:pk>/", views.delete_outing,
         name="delete_outing"),
    
    path("adoption_management", views.adoption_management,
         name="adoption_management"),
     path("add_adoption", views.add_adoption,
         name="add_adoption"),
    path("update_adoption/<int:pk>/", views.update_adoption,
         name="update_adoption"),
         path("delete_adoption/<int:pk>/", views.delete_adoption,
         name="delete_adoption"),
    
    path("guardian_management", views.guardian_management,
         name="guardian_management"),
    path("add_guardian", views.add_guardian,
         name="add_guardian"),
    path("update_guardian/<int:pk>/", views.update_guardian,
         name="update_guardian"),
         path("delete_guardian/<int:pk>/", views.delete_guardian,
         name="delete_guardian"),

     path("item_management", views.item_management,
         name="item_management"),
     path("add_item", views.add_item,
         name="add_item"),
     path("update_item/<int:pk>/", views.update_item,
         name="update_item"),
     path("delete_item/<int:pk>/", views.delete_item,
         name="delete_item"),
     
     path("itemdonation_management", views.itemdonation_management,
         name="itemdonation_management"),
     path("add_itemdonation", views.add_itemdonation,
         name="add_itemdonation"),
     path("update_itemdonation/<int:pk>/", views.update_itemdonation,
         name="update_itemdonation"),
     path("delete_itemdonation/<int:pk>/", views.delete_itemdonation,
         name="delete_itemdonation"),
     
     path("cashdonation_management", views.cashdonation_management,
         name="cashdonation_management"),
     path("add_cashdonation", views.add_cashdonation,
         name="add_cashdonation"),
     path("update_cashdonation/<int:pk>/", views.update_cashdonation,
         name="update_cashdonation"),
     path("delete_cashdonation/<int:pk>/", views.delete_cashdonation,
         name="delete_cashdonation"),
    
    path("sms_item", views.sms_item, name="sms_item"),

    path("invoice_pdf", views.render_pdf_view, name="invoice_pdf"),

    path("donation_invoice/<int:pk>/", views.donation_invoice_pdf_view, 
    name="donation_invoice"),
]

donor/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path("dashboard", views.donor_dashboard,
         name="donor_dashboard"),
    path("request_invoice", views.request_invoice,
    name="request_invoice"),
    path("add_cashdonation_donor", views.add_cashdonation_donor,
    name="add_cashdonation_donor"),
    path("cashdonation_records", views.cashdonation_records,
    name="cashdonation_records"),
    path("update_donor_user/<int:pk>/", views.update_donor_user,
    name="update_donor_user"),
]

orphansys2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    # URL to Account app
    path('', include('accounts.urls')),

    # URL to Administrator app
    path('administrator/', include('administrator.urls')),

    # URL to Administrator app
    path('donor/', include('donor.urls')),

    # URL to Error/Unavailable Page app
    path('error/', TemplateView.as_view(template_name='error/error.html'), name='error'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.


donation/models.py
from django.db import models
from donor.models import *
import datetime
from django.utils.translation import gettext as _


class Item(models.Model):
  name = models.CharField(max_length=256, unique=True)
  rqd = models.IntegerField(blank=True, default=0)
  date = models.DateField(blank=True, default=datetime.date.today)

  def __str__(self):
    return self.name


class ItemDonation(models.Model):
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
  qty = models.IntegerField()
  date = models.DateField(default=datetime.date.today)


class CashDonation(models.Model):
  DONATE_STATUS = (
        ('',  _('Select')),
        (1,  _('Rejected')),
        (2, _('Pending')),
        (3, _('Approved')),
    )

  donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
  amt = models.DecimalField(max_digits=8, decimal_places=2)
  receipt = models.ImageField(upload_to="receipts/")
  status = models.PositiveSmallIntegerField(choices=DONATE_STATUS, default=2, blank=True)
  date = models.DateField(default=datetime.date.today)
  invoice = models.FileField(upload_to="invoices/", null=True, blank=True)




donor/models.py
from django.utils.translation import gettext as _
from django.db import models
from django.conf import settings


class Donor(models.Model):
    GENDER = (
        ('',  _('Select')),
        (1,  _('Male')),
        (2, _('Female')),
        (3, _('Other')),
    )

    acc_fk = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    gender = models.PositiveSmallIntegerField(choices=GENDER, default=1)
    date_of_birth = models.DateField()
    occupation = models.CharField(max_length=100)
    annual_income = models.PositiveBigIntegerField(_('RM'))
    address = models.TextField()

    def __str__(self):
        return str(self.acc_fk.username)

administrator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import *
from accounts.models import *
from accounts.forms import *
from donor.models import *
from donor.forms import *
from orphanage.models import *
from orphanage.forms import *
from donation.models import *
from donation.forms import *
from accounts.decorators import *

import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

from twilio.rest import Client

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from django.core.mail import EmailMessage, send_mail
from django.conf import settings

from django.db import IntegrityError
from django.contrib import messages

############################################### ADMIN DASHBOARD #################################################

@allowed_users(allowed_role=[1])
def admin_dashboard(request):
    return render(request=request, template_name="administrator/dashboard.html")

############################################ DAE MODEL ###########################################################

# Estimate age
def dae(imagefile):
    filename = "C:/orphansystem/media/x-rays/" + imagefile                                       # Save image file directory
    model = tf.keras.models.load_model('C:/orphansystem/media/models/daev1.h5')                 # Load the model
    class_names = np.array(['5', '6'])                                                          # Estimated age class
    img_height = 224                                                                            # Height image requirement
    img_width = 224                                                                             # Width image requirement
    img = tf.keras.utils.load_img(filename, target_size=(img_height, img_width))                # Modify image
    img_array = tf.keras.utils.img_to_array(img)                                                # Change image into array of numbers
    img_array = tf.expand_dims(img_array, 0)                                                    # Insert an addition dimension into array
    predictions = model.predict(img_array)                                                      # Predict score
    score = tf.nn.softmax(predictions[0])                                                       # Predict estimate age class
    return class_names[np.argmax(score)]                                                        # Return result

############################################ ADMIN CRUD ###########################################################

@allowed_users(allowed_role=[1])
def admin_management(request):
    context = {
        'a_list': Account.objects.filter(role=1)
    }
    return render(request=request, template_name="administrator/admin_management.html", context=context)


@allowed_users(allowed_role=[1])
def add_admin(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST or None)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = True
            user.role = 1
            user.save()
            return redirect('admin_management')
        else:
            print(user_form.errors)
            return render(request, "administrator/add_admin.html", {'cu_form': user_form})
    return render(request, "administrator/add_admin.html", {'cu_form': CustomUserCreationForm()})


@allowed_users(allowed_role=[1])
def update_admin(request, pk):
    if request.method == "POST":
        # Pass POST data into AdminUserChangeForm
        user_form = DonorUserChangeForm(
            request.POST or None, instance=get_object_or_404(Account, pk=pk))
        # Check if form is valid
        if user_form.is_valid():
            # Save form and set privileges to True
            user = user_form.save(commit=False)
            user.is_active = True
            user.save()
        else:
            print(user_form.errors)
            context = {
                'cu_form': DonorUserChangeForm(instance=Account.objects.get(id=pk)),
            }
            return render(request, 'administrator/update_admin.html', context)
        # Redirect to User Management page
        return redirect('admin_management')
    context = {
        'cu_form': DonorUserChangeForm(instance=Account.objects.get(id=pk)),
    }
    return render(request, 'administrator/update_admin.html', context) 


@allowed_users(allowed_role=[1])
def delete_admin(request, pk):
    # Save soon-to-be-deleted donor's object
    deleted_admin = Account.objects.get(
        id=pk)
    # Delete donor record from Donor and Account
    Account.objects.get(id=pk).delete()
    messages.success(
        request, f"Admin ({deleted_admin.get_full_name()}) deleted successfully.")
    return redirect('admin_management')


#################################### DONOR CRUD ##########################################################

@allowed_users(allowed_role=[1])
def donor_management(request):
    context = {
        'd_list': Donor.objects.all()
    }
    return render(request=request, template_name="administrator/donor_management.html", context=context)


@allowed_users(allowed_role=[1])
def add_donor(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST or None)
        donor_form = DonorForm(request.POST or None)
        if user_form.is_valid() and donor_form.is_valid():
            user = user_form.save(commit=False)
            user.is_active = True
            user.save()
            donor = donor_form.save(commit=False)
            donor.acc_fk = Account.objects.get(id=user.id)
            donor.save()
            return redirect('donor_management')
        else:
            print(user_form.errors)
            print(donor_form.errors)
            return render(request, "administrator/add_donor.html", {'cu_form': user_form, 'd_form': donor_form})
    return render(request, "administrator/add_donor.html", {'cu_form': CustomUserCreationForm(), 'd_form': DonorForm()})


@allowed_users(allowed_role=[1])
def update_donor(request, pk):
    if request.method == "POST":
        user_form = DonorUserChangeForm(
            request.POST or None, instance=get_object_or_404(Account, pk=Donor.objects.get(id=pk).acc_fk.id))
        donor_form = DonorForm(
            request.POST or None, instance=get_object_or_404(Donor, pk=pk))
        if user_form.is_valid() and donor_form.is_valid():
            # Save form and set privileges to True
            user = user_form.save(commit=False)
            user.is_active = True
            user.save()
            donor = donor_form.save(commit=False)
            donor.acc_fk = Account.objects.get(id=user.id)
            donor.save()
        else:
            print(user_form.errors)
            print(donor_form.errors)
            context = {
                'cu_form': DonorUserChangeForm(instance=Account.objects.get(id=Donor.objects.get(id=pk).acc_fk.id)),
                'd_form': DonorForm(instance=Donor.objects.get(id=pk)),
            }
            return render(request, 'administrator/update_donor.html', context)
        return redirect('donor_management')
    context = {
        'cu_form': DonorUserChangeForm(instance=Account.objects.get(id=Donor.objects.get(id=pk).acc_fk.id)),
        'd_form': DonorForm(instance=Donor.objects.get(id=pk)),
        'd_list': Donor.objects.all()
    }
    return render(request, 'administrator/update_donor.html', context)


@allowed_users(allowed_role=[1])
def delete_donor(request, pk):
    # Save soon-to-be-deleted donor's object
    deleted_donor = Account.objects.get(
        id=Donor.objects.get(id=pk).acc_fk.id)
    # Delete donor record from Donor and Account
    Account.objects.get(id=Donor.objects.get(id=pk).acc_fk.id).delete()
    messages.success(
        request, f"Donor ({deleted_donor.get_full_name()}) deleted successfully.")
    return redirect('donor_management')

##################################### Orphan CRUD ########################################################################333333

@allowed_users(allowed_role=[1])
def orphan_management(request):
    context = {
        'o_list': Orphan.objects.all()
    }
    return render(request=request, template_name="administrator/orphan_management.html", context=context)


@allowed_users(allowed_role=[1])
def add_orphan(request):
    if request.method == 'POST':
        guardian_form = GuardianForm(request.POST or None, prefix='guardian')
        orphan_form = OrphanForm(request.POST or None, request.FILES, prefix='orphan')
        if guardian_form.is_valid() and orphan_form.is_valid():
            guardian = guardian_form.save(commit=False)
            orphan = orphan_form.save(commit=False)
            guardian.save()  
            orphan.guardian_fk = Guardian.objects.get(id=guardian.id)  
            orphan.save()
            orphan.dental_img = orphan_form.cleaned_data.get('dental_img')                                       
            orphan.est_age = dae(str(orphan.dental_img))
            # orphan.est_age = str(random.randint(5,6))
            orphan.save()
            return redirect('orphan_management')
        else:
            print(guardian_form.errors)
            print(orphan_form.errors)
            return render(request, "administrator/add_orphan.html", {'g_form': guardian_form, 'o_form': orphan_form})
    return render(request, "administrator/add_orphan.html", {'g_form': GuardianForm(prefix='guardian'), 'o_form': OrphanForm(prefix='orphan')})


@allowed_users(allowed_role=[1])
def update_orphan(request, pk):
    if request.method == "POST":
        guardian_form = GuardianForm(

templates/administrator/add_itemdonation.html
{% extends "base/admin_base.html" %}
{% load static crispy_forms_tags widget_tweaks %}


{% block title %}
<title>Add Item Donation | OrphanSys</title>
{% endblock %}

{% block breadcrumbs %}
<div class="pagetitle">
    <h1>Add Item Donation</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="itemdonation_management">Item Donation Management</a></li>
            <li class="breadcrumb-item active">Add Item Donation</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
{% endblock %}

{% block content %}
{% if ido_form.errors %}
<div class="alert alert-danger" role="alert">
    <ul>
        {% for field in ido_form %}
        {% for error in field.errors %}
        <li>{{ error|escape }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-6 col-sm-2">
        </div>
        <div class="col-6 col-sm-7">
            
<div class="card p-4">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-outline mb-4">
                <label class="form-label" for="form3Example3">Item</label>
                {{ ido_form.item|add_class:'form-control' | append_attr:"placeholder:Select item"}}
            </div>
            <div class="form-outline mb-4">
                <label class="form-label" for="form3Example3">Donor</label>
                {{ ido_form.donor|add_class:'form-control' | append_attr:"placeholder:Select donor"}}
            </div>
            <div class="form-outline mb-4">
                <label class="form-label" for="form3Example3">Quantity</label>
                {{ ido_form.qty|add_class:'form-control' | append_attr:"placeholder:Enter quantity"}}
            </div>
            <div class="form-outline mb-4">
              <label class="form-label" for="form3Example3">Date</label>
              {{ ido_form.date|add_class:'form-control' | append_attr:"placeholder:Select date"}}
          </div>
            <span class="float-right">
                <button type="submit" class="btn btn-primary" style="background-color: #4154f1;">Submit</button>
            </span>
        </form>
    </div>
</div>
        </div>

    </div>
</div>

<div>
    <a href="{% url 'itemdonation_management' %}" class="btn btn-primary" style="background-color: #4154f1; width: 40px; height: 40px; margin-top: 40px;">
      <i class="fa-sharp fa-solid fa-arrow-left"></i>
    </a>
</div>

{% endblock %}

{% block child_script %}
<script>
</script>
{% endblock %}

templates/administrator/adoption_management.html
{% extends "base/admin_base.html" %}
{% load static crispy_forms_tags widget_tweaks %}

{% block title %}
<title>Adoption Management | OrphanSys</title>
{% endblock %}

{% block breadcrumbs %}
<div class="pagetitle">
    <div class="row">
        <div class="col">
            <h1>Adoption Management</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Adoption Management</li>
                </ol>
            </nav>
        </div>
        <div class="col-sm m-auto d-flex justify-content-end">
            <a href="{% url 'add_adoption' %}" class="btn btn-success"><i class="fas fa-plus"></i> Add Adoption</a>
        </div>
    </div>
</div><!-- End Page Title -->
{% endblock %}

{% block content %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% elif message.tags == 'success' %}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endif %}
{% endfor %}

<div class="card p-4">
    <div class="card-body">
        <table id="adoption_table" class="display" style="width:100%">
            <thead>
                <tr>
                  <th>Orphan Name</th>
                    <th>IDN</th>
                    <th>Full Name</th>
                    <th>Date of Birth</th>
                    <th>Gender</th>
                    <th>Job</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for ad in ad_list %}
                <tr>
                    <td>{{ ad.orphan_fk }}</td>
                    <td>{{ ad.idn }}</td>
                    <td>{{ ad.first_name }} {{ ad.last_name }}</td>
                    <td>{{ ad.dob }}</td>
                    <td>{{ ad.get_gender_display }}</td>
                    <td>{{ ad.job }}</td>
                    <td>{{ ad.email }}</td>
                    <td>{{ ad.phone }}</td>
                    <td>{{ ad.add }}</td>
                    <td>
                        <a href="{% url 'update_adoption' ad.id %}">
                            <i class="fa-regular fa-pen-to-square" style="color: black;"></i>
                        </a>
                        <a href="{% url 'delete_adoption' ad.id %}">
                            <i class="fa-regular fa-trash-can" style="color: red;"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block child_script %}
<script>
    
</script>
{% endblock %}

templates/administrator/orphan_management.html
{% extends "base/admin_base.html" %}
{% load static crispy_forms_tags widget_tweaks %}

{% block title %}
<title>Orphan Management | OrphanSys</title>
{% endblock %}

{% block breadcrumbs %}
<div class="pagetitle">
    <div class="row">
        <div class="col">
            <h1>Orphan Management</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Orphan Management</li>
                </ol>
            </nav>
        </div>
        <div class="col-sm m-auto d-flex justify-content-end">
            <a href="{% url 'add_orphan' %}" class="btn btn-success"><i class="fas fa-plus"></i> Add Orphan</a>
        </div>
    </div>
</div><!-- End Page Title -->
{% endblock %}

{% block content %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% elif message.tags == 'success' %}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endif %}
{% endfor %}

<div class="card p-4">
    <div class="card-body">
        <table id="orphan_table" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>User ID</th>
                    <th>IDN</th>
                    <th>Full Name</th>
                    <th>Gender</th>
                    <th>Dental Image</th>
                    <th>Estimated Age</th>
                    <th>Guardian Name</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for o in o_list %}
                <tr>
                    <td>{{ o.id }}</td>
                    <td>{{ o.idn }}</td>
                    <td>{{ o.first_name }} {{ o.last_name }}</td>
                    <td>{{ o.get_gender_display }}</td>
                    <td>
                        {% if o.dental_img %}
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#orphanxray-{{ o.id }}" style="background-color: transparent; border-color: transparent;">
                            <i class="fa-sharp fa-solid fa-teeth-open" style="color: rgb(56, 56, 164);"></i>
                          </button>
                          <!-- Modal -->
                          <div class="modal fade" id="orphanxray-{{ o.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="orphanxray-{{ o.id }}">{{ o.first_name }} {{ o.last_name }}</h5>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <img src="{{ o.dental_img.url }}" alt="" width="100%">
                                </div>
                              </div>
                            </div>
                          </div>
                        {% endif %}
                    </td>
                    <td>{{ o.est_age }}</td>
                    <td>{{ o.guardian_fk.first_name }} {{ o.guardian_fk.last_name }}</td>
                    <td>{{ o.get_status_display }}</td>
                    <td>
                        <a href="{% url 'update_orphan2' o.id %}">
                            <i class="fa-regular fa-pen-to-square" style="color: black;"></i>
                        </a>
                        <a href="{% url 'delete_orphan' o.id %}">
                            <i class="fa-regular fa-trash-can" style="color: red;"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

{% block child_script %}
<script>

</script>
{% endblock %}

templates/administrator/outing_management.html
{% extends "base/admin_base.html" %}
{% load static crispy_forms_tags widget_tweaks %}

{% block title %}
<title>Outing Management | OrphanSys</title>
{% endblock %}

{% block breadcrumbs %}
<div class="pagetitle">
    <div class="row">
        <div class="col">
            <h1>Outing Management</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Outing Management</li>
                </ol>
            </nav>
        </div>
        <div class="col-sm m-auto d-flex justify-content-end">
            <a href="{% url 'add_outing' %}" class="btn btn-success"><i class="fas fa-plus"></i> Add Outing</a>
        </div>
    </div>
</div><!-- End Page Title -->
{% endblock %}

{% block content %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% elif message.tags == 'success' %}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endif %}
{% endfor %}

<div class="card p-4">
    <div class="card-body">
        <table id="outing_table" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Orphan Name</th>
                    <th>Date Out</th>
                    <th>Time Out</th>
                    <th>Reason</th>
                    <th>Accompany Name</th>
                    <th>Accompany IDN</th>
                    <th>Accompany Phone</th>
                    <th>Date In</th>
                    <th>Time In</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for out in out_list %}
                <tr>
                    <td>{{ out.orphan_fk }}</td>
                    <td>{{ out.date_out }}</td>
                    <td>{{ out.time_out }}</td>
                    <td>{{ out.reason }}</td>
                    <td>{{ out.accompany_first_name }} {{ out.accompany_last_name }}</td>
                    <td>{{ out.accompany_idn }}</td>
                    <td>{{ out.accompany_phone }}</td>
                    <td>{{ out.date_in }}</td>
                    <td>{{ out.time_in }}</td>
                    <td>{{ out.get_status_display }}</td>
                    <td>
                        <a href="{% url 'update_outing' out.id %}">
                            <i class="fa-regular fa-pen-to-square" style="color: black;"></i>
                        </a>
                        <a href="{% url 'delete_outing' out.id %}">
                            <i class="fa-regular fa-trash-can" style="color: red;"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block child_script %}
<script>
    
</script>
{% endblock %}

templates/administrator/pdf1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {{myvar}}
</body>
</html>